file= open("output.txt.txt", "w")
user_input= str(input("Enter text to write to the file:"))
file.write(user_input)
print("data successfully written to file")
file.close()
file1= open("output.txt.txt", "a")
user_input_2= str(input("Enter additional text to append:"))
file1.write("\n" + user_input_2)
print("data successfully appended to file")
file1.close()

file2= open("output.txt.txt", "r")
print("final contents of the file:")
print(file2.read())